# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{versatile_rjs}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Kevin IMAI TOYODA}]
  s.date = %q{2011-11-06}
  s.description = %q{VersatileRJS: Enables RJS with Rails(3.1 or higher) and jQuery.


}
  s.email = %q{condor1226@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "History.txt",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/step_definitions/versatile_rjs_steps.rb",
    "features/support/env.rb",
    "features/versatile_rjs.feature",
    "init.rb",
    "lib/versatile_rjs.rb",
    "lib/versatile_rjs/container.rb",
    "lib/versatile_rjs/page.rb",
    "lib/versatile_rjs/proxy.rb",
    "lib/versatile_rjs/proxy/default_responder.rb",
    "lib/versatile_rjs/proxy/each_proxy.rb",
    "lib/versatile_rjs/proxy/element_by_id_proxy.rb",
    "lib/versatile_rjs/proxy/element_proxy.rb",
    "lib/versatile_rjs/proxy/element_set_proxy.rb",
    "lib/versatile_rjs/proxy/expression_proxy.rb",
    "lib/versatile_rjs/proxy/framework_dependent.rb",
    "lib/versatile_rjs/proxy/jquery.rb",
    "lib/versatile_rjs/proxy/jquery/each_proxy.rb",
    "lib/versatile_rjs/proxy/jquery/element_by_id_proxy.rb",
    "lib/versatile_rjs/proxy/jquery/element_proxy.rb",
    "lib/versatile_rjs/proxy/jquery/element_set.rb",
    "lib/versatile_rjs/proxy/jquery/element_set_proxy.rb",
    "lib/versatile_rjs/proxy/jquery/selectable.rb",
    "lib/versatile_rjs/proxy/jquery/selector_proxy.rb",
    "lib/versatile_rjs/proxy/selectable.rb",
    "lib/versatile_rjs/proxy/selector_proxy.rb",
    "lib/versatile_rjs/railtie.rb",
    "lib/versatile_rjs/template_handler.rb",
    "lib/versatile_rjs/to_function_ext.rb",
    "lib/versatile_rjs/utils.rb",
    "lib/versatile_rjs/utils/.gitignore",
    "script/console",
    "script/destroy",
    "script/generate",
    "spec/spec_helper.rb",
    "spec/versatile_rjs_spec.rb",
    "versatile_rjs.gemspec"
  ]
  s.homepage = %q{http://github.com/condor/versatile_rjs}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{VersatileRJS: Enables RJS with Rails(3.1 or higher) and jQuery.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

