source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
platform :mri19 do
  gem 'activerecord-sqlite3-adapter'
end

platform :jruby do
  gem 'activerecord-jdbcsqlite3-adapter'
  gem 'jruby-openssl'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  platform :jruby do
    gem 'therubyrhino'
  end

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'



gem 'versatile_rjs', :path => '../..'
